### ISSUE TITLE
Editing Bug

### ISSUE THREAD

**Issue by Itsredd** [sweIhm/sweiproject-tg1a-3#15]
Description:

There is the Problem, when a User wants to edit a post, that it is only possible if the tags are switched.

Acceptance criteria:

A Post can be edited in the following parts (Title, text, tags, department, category)
Editing in any one of the Parts should work without saving issues.
A Post which was edited shows an original Date and the last Edit date.

**Comment by menhartFHM** [comment]
removed the "see last edited Date" criteria and opened a new Issue for that.
Other criteria are met, closing issue.
