### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by einsStudent** [sweIhm/sweiproject-tg1a-3#18]
As a user i want to have a menu bar at the top of the mainpage. By clicking through the menu i want to be able to select a other page or filter criterias for example...

Description:

The user can navigate through the menu. He can for example change the showing page or choose filter criterias. The precisely Menu entries need to be considered...

Acceptance criteria:

- A menu bar at the top of every page of the website
- The menuentries are constant
- Clickable buttons, drop down lists or controllers for filtering

**Comment by menhartFHM** [comment]
no acceptance criteria left!
Done or still open to review?

**Comment by einsStudent** [comment]
Menu is only for filter activities by title, text, department and category.
Refers to [Filter Activities](https://github.com/sweIhm/sweiproject-tg1a-3/issues/3)

**Comment by einsStudent** [comment]
assigned @Itsredd for design optimization

**Comment by einsStudent** [comment]
last commit made by @Itsredd
