### ISSUE TITLE
Show Activity Details

### ISSUE THREAD

**Issue by StMKrause** [sweIhm/sweiproject-tg1a-3#2]
#### User Story
As a user (as a student or as a professor) I want to get more details about a single post, by clicking on them.

#### Description
By selecting an activity, some details about the activity are displayed. The outcome of the activity meter is a variety of info graphics.

###### Acceptance criteria:
- a single post can be selected
- the details of the post get displayed

**Comment by menhartFHM** [comment]
dod achieved
