### ISSUE TITLE
Filter Activities

### ISSUE THREAD

**Issue by StMKrause** [sweIhm/sweiproject-tg1a-3#3]
#### User Story
As a user (as a student or as a professor) I want to filter the viewed post's by #tag date.

#### Description
Users can (without login) view (anonymized) activities and configure to viewed activities by #tag and date.

###### Acceptance criteria:
- configure the viewed post's
- choose different filter options

**Comment by menhartFHM** [comment]
Activities can only be filtered by title, moving issue to product backlog again

**Comment by menhartFHM** [comment]
-dod-

**Comment by einsStudent** [comment]
TODO: Filter for tags and date.
