### ISSUE TITLE
Add a "load more" button at the bottom of the activity board

### ISSUE THREAD

**Issue by menhartFHM** [sweIhm/sweiproject-tg1a-3#8]
As a student I want to see older posts by clicking on a "load more" button at the bottom of the activity board.

Description:

The activity board should only display the most recent 50 posts when looking at the activity board. If a user wants to see older posts he should be able to click on a "load more" button at the bottom of the page, which should request more data to display from the server. The user can keep loading new posts until he reached the oldest post.

Acceptance criteria:

 - By default, only load and display the most recent 50 posts from the database
 - Add a "load more" button to the bottom of the activity board
 - By clicking on the "load more" button 50 more posts should be fetched from the database
 - Allow user to keep loading older posts until all posts are displayed

**Comment by einsStudent** [comment]
initialy only 20 activities are shown. By clicking "load more.." (last row in activity-table), 20 more activities will show.
